OUTPUT_DIR: "./exp_prw"
INPUT:
  DATASET: "PRWUnsupervised"
  DATA_ROOT: "data/PRW"
  BATCH_SIZE_TRAIN: 8
SOLVER:
  MAX_EPOCHS: 50
  LR_DECAY_MILESTONES: [8]
MODEL:
  LOSS:
    LUT_SIZE: 482
    CQ_SIZE: 500
